language: python
python:
  - 2.7

install:
  - pip install -r requirements.txt

script:
  - python monitor.py -c config/travis.yml.build --debug
  - python reactor.py -c config/travis.yml.build --debug
  - python monitor.py -c config/travis.yml.build --debug
  - python reactor.py -c config/travis.yml.build --debug
  - python monitor.py -c config/travis.yml.build --debug
  - python reactor.py -c config/travis.yml.build --debug
  - python monitor.py -c config/travis.yml.build --debug
  - python reactor.py -c config/travis.yml.build --debug
